package com.apex.livebos.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-07T09:51:45.449+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "LBDocumentWebService", 
                  wsdlLocation = "http://222.175.251.218:10000/service/LBDocument?wsdl",
                  targetNamespace = "http://ws.livebos.apex.com/") 
public class LBDocumentWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.livebos.apex.com/", "LBDocumentWebService");
    public final static QName LBDocumentServiceImplPort = new QName("http://ws.livebos.apex.com/", "LBDocumentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://222.175.251.218:10000/service/LBDocument?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LBDocumentWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://222.175.251.218:10000/service/LBDocument?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LBDocumentWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LBDocumentWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBDocumentWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LBDocumentWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LBDocumentWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LBDocumentWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LBDocumentService
     */
    @WebEndpoint(name = "LBDocumentServiceImplPort")
    public LBDocumentService getLBDocumentServiceImplPort() {
        return super.getPort(LBDocumentServiceImplPort, LBDocumentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LBDocumentService
     */
    @WebEndpoint(name = "LBDocumentServiceImplPort")
    public LBDocumentService getLBDocumentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(LBDocumentServiceImplPort, LBDocumentService.class, features);
    }

}
