package com.apex.livebos.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-17T08:47:34.791+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ws.livebos.apex.com/", name = "LBDocumentService")
@XmlSeeAlso({ObjectFactory.class})
public interface LBDocumentService {

    @WebMethod
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.DeleteDocument")
    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.DeleteDocumentResponse")
    @WebResult(name = "LBEResult", targetNamespace = "")
    public com.apex.livebos.ws.LbeResult deleteDocument(
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(name = "objectName", targetNamespace = "")
        java.lang.String objectName,
        @WebParam(name = "columnName", targetNamespace = "")
        java.lang.String columnName,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "entryNo", targetNamespace = "")
        java.lang.String entryNo
    );

    @WebMethod
    @RequestWrapper(localName = "putDocument", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.PutDocument")
    @ResponseWrapper(localName = "putDocumentResponse", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.PutDocumentResponse")
    @WebResult(name = "LBEResult", targetNamespace = "")
    public com.apex.livebos.ws.LbeResult putDocument(
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(name = "document", targetNamespace = "")
        com.apex.livebos.ws.Document document,
        @WebParam(name = "objectName", targetNamespace = "")
        java.lang.String objectName,
        @WebParam(name = "columnName", targetNamespace = "")
        java.lang.String columnName,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @RequestWrapper(localName = "queryEntry", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.QueryEntry")
    @ResponseWrapper(localName = "queryEntryResponse", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.QueryEntryResponse")
    @WebResult(name = "DocumentEntryResult", targetNamespace = "")
    public com.apex.livebos.ws.DocumentEntryResult queryEntry(
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(name = "objectName", targetNamespace = "")
        java.lang.String objectName,
        @WebParam(name = "columnName", targetNamespace = "")
        java.lang.String columnName,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://ws.livebos.apex.com/", className = "com.apex.livebos.ws.GetDocumentResponse")
    @WebResult(name = "DocumentResult", targetNamespace = "")
    public com.apex.livebos.ws.DocumentResult getDocument(
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(name = "objectName", targetNamespace = "")
        java.lang.String objectName,
        @WebParam(name = "columnName", targetNamespace = "")
        java.lang.String columnName,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "entryNo", targetNamespace = "")
        java.lang.String entryNo
    );
}
